name: Acquiring System CI

# Bu robot ne zaman çalışsın?
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    name: Build & Test Microservices
    runs-on: ubuntu-latest # Robotun işletim sistemi (Linux)

    steps:
    # 1. Kodu GitHub'dan sanal makineye çek
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Sanal makineye .NET 10 SDK kur
    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    # 3. Gateway API'yi Derle
    - name: Restore & Build Gateway API
      working-directory: ./src/Services/Gateway/Gateway.Api
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore

    # 4. Merchant API'yi Derle
    - name: Restore & Build Merchant API
      working-directory: ./src/Services/Merchant/Merchant.Api
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
        
    - name: Run Unit Tests
      working-directory: ./src/Services/Gateway/Gateway.UnitTests
      run: dotnet test --verbosity normal

    # 5. Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose